const SUPABASE_URL="https://uryjmibcdfjfxoljrigt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_uYbJw0ARCCkCpQ9QB6FxaQ_JrIxtOOp";
const supabaseClient=supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
let products=[];let cart=JSON.parse(localStorage.getItem("br_cart")||"[]");
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const categoryLabel=v=>({"mobiles":"Mobiles","electronics":"Electronics","fashion":"Fashion","home":"Home","beauty":"Beauty","toys-games":"Toys & Games","accessories":"Accessories","sports":"Sports","grocery":"Grocery","other":"Other"}[String(v||"").toLowerCase()]||v||"Other");
async function loadProducts(){const s=document.getElementById("status");s.textContent="Products load ho rahe hain...";try{const {data,error}=await supabaseClient.from("products").select("id,product_name,price,stock,category,image_url").order("id",{ascending:false});if(error)throw error;products=data||[];s.textContent=`${products.length} Products`;renderProducts()}catch(e){console.error(e);s.textContent="Connection error";document.getElementById("productGrid").innerHTML=`<div style="grid-column:1/-1;background:#fff;padding:25px;border-radius:16px;text-align:center">❌ Products load नहीं हुए।<br><small>${esc(e.message||e)}</small></div>`}}
function renderProducts(){const g=document.getElementById("productGrid"),q=(document.getElementById("search").value||"").toLowerCase().trim(),c=(document.getElementById("category").value||"all").toLowerCase();const f=products.filter(p=>String(p.product_name||"").toLowerCase().includes(q)&&(c==="all"||String(p.category||"").toLowerCase()===c));if(!f.length){g.innerHTML=`<div style="grid-column:1/-1;background:#fff;padding:30px;border-radius:16px;text-align:center"><h3>😔 Product nahi mila</h3><p>Dusra search/category try karein.</p></div>`;return}g.innerHTML=f.map(p=>{const st=Number(p.stock||0),pr=Number(p.price||0);return `<article class="product-card" onclick="openProduct(${JSON.stringify(p.id)})"><div class="product-image"><img src="${esc(p.image_url)}" alt="${esc(p.product_name)}" onerror="this.src='https://placehold.co/600x600?text=Product'"></div><h3>${esc(p.product_name)}</h3><p class="brand-line">🏷️ ${esc(categoryLabel(p.category))}</p><p class="price">₹${pr.toLocaleString("en-IN")}</p><p class="stock">${st>0?"✓ Stock available":"Out of stock"}</p><div class="card-actions"><button class="add" onclick="event.stopPropagation();addToCart(${JSON.stringify(p.id)})" ${st<=0?"disabled":""}>🛒 Cart</button><button class="buy" onclick="event.stopPropagation();openProduct(${JSON.stringify(p.id)})">⚡ Buy Now</button></div></article>`}).join("")}
function openProduct(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;const m=document.getElementById("detailModal");m.classList.remove("hidden");m.innerHTML=`<div class="modal-card"><button class="close" onclick="closeDetail()">×</button><div class="detail-image"><img src="${esc(p.image_url)}" alt="${esc(p.product_name)}"></div><h2>${esc(p.product_name)}</h2><p>🏷️ Category: ${esc(categoryLabel(p.category))}</p><h2>₹${Number(p.price||0).toLocaleString("en-IN")}</h2><p>${Number(p.stock||0)>0?"✅ Stock available":"❌ Out of stock"}</p><button class="full" onclick="addToCart(${JSON.stringify(p.id)});closeDetail()">🛒 Add to Cart</button></div>`}
function closeDetail(){document.getElementById("detailModal").classList.add("hidden")}
function addToCart(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;const e=cart.find(x=>String(x.id)===String(id));if(e){if(e.quantity>=Number(p.stock||0)){alert("❌ Itna stock available nahi hai.");return}e.quantity++}else cart.push({...p,quantity:1});saveCart();updateCartButton();alert("✅ Product cart mein add ho gaya!")}
function saveCart(){localStorage.setItem("br_cart",JSON.stringify(cart))}
function updateCartButton(){document.getElementById("cartCount").textContent=cart.reduce((s,x)=>s+Number(x.quantity||0),0)}
function openCart(){const m=document.getElementById("cartModal");m.classList.remove("hidden");const t=cart.reduce((s,x)=>s+Number(x.price||0)*Number(x.quantity||0),0);m.innerHTML=`<div class="modal-card"><button class="close" onclick="closeCart()">×</button><h2>🛒 Your Cart</h2>${cart.length?cart.map(x=>`<div style="display:flex;gap:10px;padding:12px 0;border-bottom:1px solid #eee"><img src="${esc(x.image_url)}" style="width:70px;height:70px;object-fit:contain;border-radius:10px;background:#f5f5f5"><div style="flex:1"><b>${esc(x.product_name)}</b><div>₹${Number(x.price||0)} × ${x.quantity}</div><div style="margin-top:7px"><button onclick="changeQuantity(${JSON.stringify(x.id)},-1)">−</button> <b>${x.quantity}</b> <button onclick="changeQuantity(${JSON.stringify(x.id)},1)">+</button> <button onclick="removeFromCart(${JSON.stringify(x.id)})">🗑️</button></div></div></div>`).join(""):`<div style="padding:30px;text-align:center">🛒 Cart khaali hai</div>`}<h2>Total: ₹${t.toLocaleString("en-IN")}</h2>${cart.length?`<button class="full" onclick="showCODForm()">📦 Cash on Delivery Order</button>`:""}</div>`}
function closeCart(){document.getElementById("cartModal").classList.add("hidden")}
function changeQuantity(id,d){const x=cart.find(p=>String(p.id)===String(id));if(!x)return;const p=products.find(p=>String(p.id)===String(id));x.quantity+=d;if(x.quantity<=0)cart=cart.filter(p=>String(p.id)!==String(id));if(p&&x.quantity>Number(p.stock||0))x.quantity=Number(p.stock||0);saveCart();updateCartButton();openCart()}
function removeFromCart(id){cart=cart.filter(p=>String(p.id)!==String(id));saveCart();updateCartButton();openCart()}
function showCODForm(){const m=document.getElementById("cartModal");m.innerHTML=`<div class="modal-card"><button class="close" onclick="closeCart()">×</button><h2>📦 Cash on Delivery</h2><input id="customerName" placeholder="👤 Full Name" style="width:100%;padding:14px;margin:7px 0;border:1px solid #ddd;border-radius:10px"><input id="customerPhone" placeholder="📱 Mobile Number" type="tel" style="width:100%;padding:14px;margin:7px 0;border:1px solid #ddd;border-radius:10px"><textarea id="customerAddress" placeholder="🏠 Complete Delivery Address" rows="4" style="width:100%;padding:14px;margin:7px 0;border:1px solid #ddd;border-radius:10px"></textarea><input id="customerPincode" placeholder="📍 Pincode" inputmode="numeric" style="width:100%;padding:14px;margin:7px 0;border:1px solid #ddd;border-radius:10px"><button class="full" onclick="placeCODOrder()">✅ Place COD Order</button></div>`}
function placeCODOrder(){const n=document.getElementById("customerName").value.trim(),ph=document.getElementById("customerPhone").value.trim(),a=document.getElementById("customerAddress").value.trim(),pin=document.getElementById("customerPincode").value.trim();if(!n||ph.length<10||!a||!pin){alert("⚠️ Please sabhi details sahi se bharein.");return}const t=cart.reduce((s,x)=>s+Number(x.price||0)*Number(x.quantity||0),0);let msg=`🛒 *BR DIGITAL MARKETPLACE - NEW ORDER*\n\n👤 Customer: ${n}\n📱 Mobile: ${ph}\n🏠 Address: ${a}\n📍 Pincode: ${pin}\n\n📦 Products:\n`;cart.forEach(x=>msg+=`\n• ${x.product_name}\n  Qty: ${x.quantity}\n  Price: ₹${x.price}\n`);msg+=`\n💰 *Total: ₹${t}*\n💳 Payment: Cash on Delivery`;const whatsappNumber="919229864665";window.location.href=`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(msg)}`;cart=[];saveCart();updateCartButton()}
document.getElementById("search").addEventListener("input",renderProducts);document.getElementById("category").addEventListener("change",renderProducts);document.addEventListener("DOMContentLoaded",()=>{updateCartButton();loadProducts()});
